name: build

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: # Este é o nome que você vai buscar no Ruleset depois
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar GraalVM 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache dos pacotes Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Executar Testes e Validar Cobertura
        run: mvn clean verify